@startuml
'tomcateNio接入类图
class NioEndpoint {
    - NioSelectorPool;
    - ServerSocketChannel;
    - List<PollerEvent>
    - List<NioChannel>
}
class NioSelectorPool {
}
class ServerSocketChannel {
}
class PollerEvent {
}
class NioChannel{
    - SocketBufferHandler;
    - SocketChannel;
    - NioSocketWrapper;
}
class NioBlockingSelector{

}

class SocketBufferHandler{

}
class SocketChannel{

}
class NioSocketWrapper{
NioSelectorPool
List<NioChannel>
Poller
}
@enduml
